// <auto-generated />
namespace IMedDataSourceMSSQL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class AddVisitsAndPhone : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddVisitsAndPhone));
        
        string IMigrationMetadata.Id
        {
            get { return "202007140926116_Add Visits And Phone"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
